apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: vote
        image: myvotingregistry.azurecr.io/myvotingregistry/vote:v1
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
